### ISSUE TITLE
Add support for Netplan

### ISSUE THREAD

**Issue by vpetersson** [Screenly/wizard.screenly.io#1]
Screenly V2 will initially be using [Netplan](https://wiki.ubuntu.com/Netplan). We need to add support to the wizard for generating Netplan.

**Comment by vpetersson** [comment]
Break down the page into multiple steps:

 * Step 1: `Select version: Screenly Pro v1 | Screenly Pro v2 (Netplan)`
   * If v2, disable NTP configuration
 * If v1, view use the existing config
 * If v2, use the Netplan format and the downloaded file should be call `netplan.yaml`

Here's an example of a v2 file for just DHCP:

```
network:
    version: 2
    ethernets:
        all-en:
            match:
                name: "en*"
            dhcp4: true
        all-eth:
            match:
                name: "eth*"
            dhcp4: true
```

Here's one with Wifi (and DHCP on `en*`):

```
network:
    version: 2
    
    # Our image uses systemd-networkd to manage the network. 
    # Everything worked without that setting, anyhow
    # renderer: networkd 
  
    wifis:
        wlan0:
            # It's false by default. 
            dhcp4: true  
            access-points:
                "AP-name":
                    password: "the password"
    ethernets:
        all-en:
            match:
                name: "en*"
            dhcp4: true
        all-eth:
            match:
                name: "eth*"
            dhcp4: true
```

**Comment by vpetersson** [comment]
DNS can be configured as follows:
```
ethernets:
  id0:
    [...]
    nameservers:
      search: [lab, home]
      addresses: [8.8.8.8, FEDC::1]
```

See this page for more info:
http://people.canonical.com/~mtrudel/netplan/

**Comment by vpetersson** [comment]
Deliverables: 
 * The user must be able to select between the two options
 * The old option must be able to export "legacy" `network.ini` files
 * The new option must be able to generate new `network.yaml` files
   * The output must be able to generate configuration files of various types, including: 
      * Ethernet with DHCP
      * Ethernet with static IP and custom DNS
      * WiFi with static IP
      * WiFi with DHCP

**Comment by tehmoose** [comment]
Hello there.

Questions regarding Netplan:
- I suppose there is no way to specify that SSID for WiFi connection is hidden?
- Is there going to be a single wired interface, and can its name be determined (I mean, is it going to be eth0, en0 or anything particular) or do I need to use generalized constructions like this:
```
    ethernets:
        all-en:
            match:
                name: "en*"
            dhcp4: true
        all-eth:
            match:
                name: "eth*"
            dhcp4: true
```
- Almost the same questions go for WiFi interface (Is there a single interface or not? Does it have an id?)
