### ISSUE TITLE
Ethernet doesn't work when NetworkManager is selected

### ISSUE THREAD

**Issue by renat-galimov** [Screenly/wizard.screenly.io#13]
networkd syntax is not supported by the NetworkManager. 

From the [netplan's documentation](https://netplan.io/reference#properties-for-device-type-ethernets):

> Current interface name. Globs are supported, and the primary use case for matching on names, as selecting one fixed name can be more easily achieved with having no match: at all and just using the ID (see above). Note that currently only networkd supports globbing, NetworkManager does not.

**Comment by rusko124** [comment]
Hm, my suggestion:
- If the "Use Network Manager" checkbox is enabled, set *renderer: NetworkManager* only for wlan0. For wired connection, add the mac address field on which the match will be performed and then *renderer: NetworkManager* use for ethernets too.
What you think?
Somethink like:
```
network:
  version: 2
  ethernets:
    all-en:
      match:
        name: "en*"
      dhcp4: true
    all-eth:
      match:
        name: "eth*"
      dhcp4: true
  wifis:
    wlan0:
      renderer: NetworkManager
      access-points:
        "ssid":
          password: "pass"
      dhcp4: true
```
```
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    all-en:
      match:
        macaddress: 00:11:22:33:44:55
      dhcp4: true
    all-eth:
      match:
        macaddress: 00:11:22:33:44:55
      dhcp4: true
  wifis:
    wlan0:
      access-points:
        "ssid":
          password: "pass"
      dhcp4: true
```

**Comment by renat-galimov** [comment]
It doesn't look very professional. We don't want users to input MAC addresses. Is it possible to match exact interface names?

**Comment by rusko124** [comment]
This is just an example, for direction. I didn't work with wizard.screenly.io and don't know why need to use eth* instead of eth0 since raspberry pi uses this interface.

**Comment by renat-galimov** [comment]
That’s how it was for historical reasons. Feel free to do an exact match instead of a glob

Thank you

**Comment by rusko124** [comment]
@renat-galimov 
Is that what you meant?
```
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eth0:
      dhcp4: true
  wifis:
    wlan0:
      access-points:
        "pass":
          password: "pass"
      dhcp4: true
```

We can also leave the config with blob if don't selected NetworkManager, what do you think?
