### ISSUE TITLE
The wizard doesn't support quotes in SSID and passphrase

### ISSUE THREAD

**Issue by femdom** [Screenly/wizard.screenly.io#9]
Try to create a config for an AP with SSID `"redmi"` and passphrase `1234567"`, and it will generate a wrong-formatted YAML.

**Comment by femdom** [comment]
```
network:
  version: 2
  wifis:
    wlan0:
      access-points:
        ""Redmi"":
          password: "1234567""
      dhcp4: true
```
